package gowsdl

var serverHeaderTmpl = `
// Code generated by gowsdl DO NOT EDIT.

package {{.}}

import (
	"fmt"
	"errors"
	"reflect"
	"strings"
	"github.com/mantikafasi/goxml"
	"net/http"

	{{/*range .Imports*/}}
		{{/*.*/}}
	{{/*end*/}}
)

`
